apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wil42-playground
  name: wil42-playground
  namespace: dev
spec:
  template:
    metadata:
      labels:
        app: wil42-playground
    spec:
      containers:
        - name: wil42-playground
          image: wil42/playground:v1
          ports:
            - containerPort: 8888
  selector:
    matchLabels:
      app: wil42-playground
  replicas: 1
